---
apiVersion: v1
kind: ConfigMap
metadata:
  name: support-console-bff-config
  namespace: support-console
data:
  # Server configuration
  PORT: "8080"
  HEALTH_PORT: "8082"
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  # CORS configuration
  CORS_ORIGINS: "http://support-console-svc.support-console.svc.cluster.local:8080,https://support-console.local"
  # External API configuration
  EXTERNAL_API_TIMEOUT: "30000"
  EXTERNAL_API_RETRY_COUNT: "3"
  # Environment
  NODE_ENV: "production"
