---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-console-bff
  namespace: support-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-console-bff
  template:
    metadata:
      labels:
        app: support-console-bff
    spec:
      containers:
        - name: support-console-bff
          image: beyondtrust-docker.jfrog.io/beyondtrust/support-console-bff:2.2.0
          ports:
            - containerPort: 8080
