---
apiVersion: v1
kind: ConfigMap
metadata:
  name: support-console-bff-config
  namespace: support-console
data:
  # Server configuration
  PORT: "8080"
  HEALTH_PORT: "8082"
  # Logging configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  # CORS configuration
  CORS_ORIGINS: "http://support-console-svc.support-console.svc.cluster.local:8080,https://support-console.local"
  # External API configuration
  EXTERNAL_API_TIMEOUT: "30000"
  EXTERNAL_API_RETRY_COUNT: "3"
  # Environment
  NODE_ENV: "production"

---
apiVersion: v1
kind: Secret
metadata:
  name: support-console-bff-secrets
  namespace: support-console
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # echo -n "your-secret-value" | base64
  # External API authentication
  external-api-key: eW91ci1leHRlcm5hbC1hcGkta2V5 # your-external-api-key
  # Internal service authentication
  service-auth-token: eW91ci1zZXJ2aWNlLWF1dGgtdG9rZW4= # your-service-auth-token

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: support-console-bff-sa
  namespace: support-console

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-console-bff
  namespace: support-console
  labels:
    app: support-console-bff
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-console-bff
  template:
    metadata:
      labels:
        app: support-console-bff
        component: backend
    spec:
      serviceAccountName: support-console-bff-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: support-console-bff
          # Replace with your actual BFF image
          image: beyondtrust-docker.jfrog.io/beyondtrust/support-console-bff:2.2.0
          imagePullPolicy: Always
          command: ["node", "server.js"]
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8082
              name: health
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: support-console-bff-config
                  key: PORT
            - name: HEALTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: support-console-bff-config
                  key: HEALTH_PORT
            - name: EXTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: support-console-bff-secrets
                  key: external-api-key
            - name: SERVICE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: support-console-bff-secrets
                  key: service-auth-token
          envFrom:
            - configMapRef:
                name: support-console-bff-config
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/ready
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
            - name: tmp-volume
              mountPath: /tmp
            - name: app-cache
              mountPath: /app/.cache
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
        - name: app-cache
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: support-console-bff-svc
  namespace: support-console
  labels:
    app: support-console-bff
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: health
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: support-console-bff

---
# HorizontalPodAutoscaler for BFF (optional)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: support-console-bff-hpa
  namespace: support-console
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: support-console-bff
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
