---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-console-bff
  namespace: support-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-console-bff
  template:
    metadata:
      labels:
        app: support-console-bff
    spec:
      containers:
        - name: support-console-bff
          image: node:18-alpine
          command:
            [
              "node",
              "-e",
              "const http = require('http'); const server = http.createServer((req, res) => { res.writeHead(200, {'Content-Type': 'text/plain'}); res.end('Hello from support-console-bff\\n'); }); server.listen(8080, '0.0.0.0', () => { console.log('Server running on port 8080'); });",
            ]
          ports:
            - containerPort: 8080
