apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: support-console

resources:
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

# Labels are defined in individual resource files

# Environment-specific patches
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: support-console-bff
      namespace: support-console
    spec:
      template:
        spec:
          containers:
          - name: support-console-bff
            env:
            - name: ENVIRONMENT
              value: "local"

# Images are set in deployment.yaml

# ConfigMap from environment file
configMapGenerator:
  - name: support-console-bff-env
    env: support-console-bff.env
    options:
      disableNameSuffixHash: true
