---
apiVersion: v1
kind: Secret
metadata:
  name: support-console-bff-secrets
  namespace: support-console
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # echo -n "your-secret-value" | base64
  # External API authentication
  external-api-key: eW91ci1leHRlcm5hbC1hcGkta2V5 # your-external-api-key
  # Internal service authentication
  service-auth-token: eW91ci1zZXJ2aWNlLWF1dGgtdG9rZW4= # your-service-auth-token
