apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy-auth-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rliaogithub/nginx-argo-app.git
    targetRevision: HEAD
    path: k8s/oauth2-proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
