# k8s/kustomization.yaml
resources:
  - istio/gateway.yaml
  - nginx/
  # - support-console/  # Commented out for troubleshooting
  # - support-console-bff/  # Moved to independent ArgoCD application
