apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
  namespace: default
data:
  config.yaml: |
    issuer: "http://dex.istio.local/dex"
    storage:
      type: memory

    web:
      http: 0.0.0.0:5556

    # Static test user, bcrypt hash for 'Password123!'
    enablePasswordDB: true
    staticPasswords:
    - email: "ron@example.com"
      hash: ""$2b$10$wJi05KxiEL9flhGE6zYKq.5IOWun8EenzfiLK7cxJiL7SiWXc9/Ei"
      username: "ron"
      userID: "0001"

    # OAuth2-Proxy client
    staticClients:
    - id: oauth2-proxy
      name: "OAuth2 Proxy (Local)"
      secret: "G5pYCYuon3LFdMltKxmJPJwpDpbatdL9"
      redirectURIs:
      - "http://oauth2-proxy.local/oauth2/callback"

    oauth2:
      skipApprovalScreen: false
