---
apiVersion: v1
kind: ConfigMap
metadata:
  name: support-console-config
  namespace: support-console
data:
  # Environment configuration
  NODE_ENV: "production"
  # Nginx configuration
  NGINX_PORT: "8080"
  NGINX_HEALTH_PORT: "8181"
  NGINX_METRICS_PORT: "8083"
  # Logging configuration
  LOG_LEVEL: "info"
