---
apiVersion: v1
kind: Secret
metadata:
  name: support-console-secrets
  namespace: support-console
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # echo -n "your-secret-value" | base64
  # Frontend specific secrets
  api-key: eW91ci1hcGkta2V5 # your-api-key
  # Session secrets
  session-secret: eW91ci1zZXNzaW9uLXNlY3JldA== # your-session-secret
