---
apiVersion: v1
kind: Service
metadata:
  name: support-console-svc
  namespace: support-console
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: support-console
