apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.9.0
          args:
            - --provider=oidc
            - --http-address=0.0.0.0:4180
            - --cookie-secure=false # HTTP for local; set true when using HTTPS
            - --cookie-samesite=lax
            - --cookie-domain=oauth2-proxy.local
            - --redirect-url=http://oauth2-proxy.local/oauth2/callback
            - --email-domain=*
            - --set-authorization-header=true
            - --set-xauthrequest=true
            - --pass-authorization-header=true
            - --pass-access-token=true
            - --pass-user-headers=true
            # OIDC endpoints (hybrid approach for cluster-external compatibility)
            - --oidc-issuer-url=http://dex.istio.local/dex
            - --login-url=http://dex.istio.local/dex/auth
            - --redeem-url=http://dex.default.svc.cluster.local:5556/dex/token
            - --oidc-jwks-url=http://dex.default.svc.cluster.local:5556/dex/keys
            - --skip-oidc-discovery=true
            # Example upstream (protect your nginx app)
            - --upstream=http://nginx.default.svc.cluster.local:80/
            # Extra logging
            - --standard-logging=true
            - --request-logging=true
            - --auth-logging=true
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: OAUTH2_PROXY_CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: OAUTH2_PROXY_CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: OAUTH2_PROXY_COOKIE_SECRET
          ports:
            - name: http
              containerPort: 4180
          readinessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 5
            periodSeconds: 5
