apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: default
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
  OAUTH2_PROXY_CLIENT_SECRET: "G5pYCYuon3LFdMltKxmJPJwpDpbatdL9"
  OAUTH2_PROXY_COOKIE_SECRET: "M0bJgGwHLyN7cTG4fJTJcSpV8oe3XP5ieee1PEYeNSc="
