apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  hosts:
    - oauth2-proxy.local
  gateways:
    - app-gateway
  http:
    - route:
        - destination:
            host: oauth2-proxy.default.svc.cluster.local
            port:
              number: 4180
