apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  hosts:
    - oauth2-proxy.local
  gateways:
    - app-gateway
  http:
    # 1) Drop malicious X-Forwarded-Uri (generic interaction domains)
    - match:
        - headers:
            x-forwarded-uri:
              regex: "(?i)^.*(?:interact\\.sploit|burpcollaborator|oast|dnslog|https?://).*$"
      directResponse:
        status: 404
        body: { string: "Not Found" }

    # 2) Drop abusive rd= redirect params (external URLs / interaction domains)
    - match:
        - queryParams:
            rd:
              regex: "(?i)^.*(?:interact\\.sploit|burpcollaborator|oast|dnslog|https?://).*$"
      directResponse:
        status: 404
        body: { string: "Not Found" }

    - match:
        - uri:
            prefix: /oauth2/
      route:
        - destination:
            host: oauth2-proxy.default.svc.cluster.local
            port:
              number: 4180
